# Q1. What are the benefits of the built-in array package, if any?
The Array is built-in Python, which only means that you don’t need to download and install it because it comes with native Python for sure.
it must bring some benefits. That is the so-call “trade-off”. In this case, Python Array will have a smaller size than Python List.This is because the type code of the array is fixed and the number of bytes of each item is also fixed. It loses some flexibility but has less overhead.

# Q2. What are some of the array package's limitations?
Python array can only contain elements with a certain type.
You still need to import array.


# Q3. Describe the main differences between the array and numpy packages.
 A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.
 A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

A common beginner question is what is the real difference here. The answer is performance. Numpy data structures perform better in:

Size - Numpy data structures take up less space
Performance - they have a need for speed and are faster than lists
Functionality - SciPy and NumPy have optimized functions such as linear algebra operations built in.

# Q4. Explain the distinctions between the empty, ones, and zeros functions.

At such sizes, basically the only difference between numpy.empty and numpy.zeros is that empty uses malloc and zeros uses calloc.

If you want to check this yourself, you can look at the code for empty and zeros in the NumPy source repository and follow the code paths down to the malloc and calloc calls.

# Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

At such sizes, basically the only difference between numpy.empty and numpy.zeros is that empty uses malloc and zeros uses calloc.

If you want to check this yourself, you can look at the code for empty and zeros in the NumPy source repository and follow the code paths down to the malloc and calloc calls.

# Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

When a numpy array is combined with a single_value operand such as scalar through addition. Then that perticular scalar value get added in every element of numpy array. Example shown below.

In [1]:
import numpy as np
lst = [2,3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]
v = np.array(lst)
v = v + 2
print(v)


[ 4.    5.    9.9   5.3   8.9   2.11 12.3  14.9 ]


# Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

It will add or multiply for += or *=  those symbols respectivly. 

In [2]:
lst = [2,3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]
v = np.array(lst)
v+= 2
print(v)

[ 4.    5.    9.9   5.3   8.9   2.11 12.3  14.9 ]


# Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?
Yes numpy array contain fixed-length strings. If you allocat a longer string to one of these arrays it will throw error.

# Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

If we use another array instead of a scalar, the elements of both arrays will be component-wise combined for both multiplication as well addition operation. 

Join a sequence of arrays along an existing axis. The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default). The axis along which the arrays will be joined.

# Q10. What is the best way to use a Boolean array to mask another array?

A more powerful pattern is to use Boolean arrays as masks, to select particular subsets of the data themselves. Returning to our x array from before, suppose we want an array of all values in the array that are less than, say, 5:

In [26]:
x
Out[26]:
array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])
We can obtain a Boolean array for this condition easily, as we've already seen:

In [27]:
x < 5
Out[27]:
array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]], dtype=bool)
Now to select these values from the array, we can simply index on this Boolean array; this is known as a masking operation:

In [28]:
x[x < 5]
Out[28]:
array([0, 3, 3, 3, 2, 4])
What is returned is a one-dimensional array filled with all the values that meet this condition; in other words, all the values in positions at which the mask array is True.


# Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

The Python statistics module also provides functions to calculate the standard deviation. We can find pstdev() and stdev(), std(). The first function takes the data of an entire population and returns its standard deviation. The second function takes data from a sample and returns an estimation of the population standard deviation.

# 12. What is the dimensionality of a Boolean mask-generated array?
Dimesionality of Boolean mask-generated arrya is 1 Dimensional array.